INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (1, N'Material', N'Toàn váy', '0', N'Vải lụa', '', N'/productMaterialDefaults/77777fee-87e5-468d-988b-9b48413eaba9/normalMap.png', N'/productMaterialDefaults/77777fee-87e5-468d-988b-9b48413eaba9/roughnessMap.png', N'/productMaterialDefaults/77777fee-87e5-468d-988b-9b48413eaba9/metalnessMap.png', 1); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (2, N'Back_FRONT_2239', N'Phía sau áo', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (3, N'Button_FRONT_2249', N'Khuy cài cúc', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (4, N'Collar_FRONT_2229', N'Cổ áo', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (5, N'Front_FRONT_2234', N'Phía trước áo', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (6, N'Lower_Left_FRONT_2224', N'Viền cổ tay trái', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (7, N'Lower_Right_FRONT_2214', N'Viền cổ tay phải', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (8, N'Material115145', N'Cúc áo', '0', N'Nhựa', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (9, N'PT_FABRIC_FRONT_2281', N'Lỗ cài cúc', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (10, N'Pocket_FRONT_2244', N'Túi áo', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (11, N'Upper_Left_FRONT_2219', N'Cánh tay trái', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (12, N'Upper_Right_FRONT_2209', N'Cánh tay phải', '0', N'Cotton', '', '', '', '', 2); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (13, N'lambert_M', N'Toàn váy', '0', N'Vải lụa', N'/productMaterialDefaults/4bbd7fc3-51cf-4998-8846-15d1a0cd5e4f/aoMap.png', N'/productMaterialDefaults/4bbd7fc3-51cf-4998-8846-15d1a0cd5e4f/normalMap.png', N'/productMaterialDefaults/4bbd7fc3-51cf-4998-8846-15d1a0cd5e4f/roughnessMap.png', N'/productMaterialDefaults/4bbd7fc3-51cf-4998-8846-15d1a0cd5e4f/metalnessMap.png', 3); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (14, N'01_-_Default', N'Toàn áo', '0', N'Cotton', '', '', '', '', 4); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (15, N'Material', N'Toàn váy', '0', N'Polyester', '', N'/productMaterialDefaults/8c4b809a-91e5-4258-b813-dee956e87ef5/normalMap.png', N'/productMaterialDefaults/8c4b809a-91e5-4258-b813-dee956e87ef5/roughnessMap.png', N'/productMaterialDefaults/8c4b809a-91e5-4258-b813-dee956e87ef5/metalnessMap.png', 5); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (16, N'wire_134006006', N'Toàn bộ', '0', N'Cotton', '', '', '', '', 6); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (17, N'Garments_Mat1', N'Váy', '0', N'Cotton', N'/productMaterialDefaults/93da7ef6-9c75-4be0-b9bc-f5255d837ad5/aoMap.png', N'/productMaterialDefaults/93da7ef6-9c75-4be0-b9bc-f5255d837ad5/normalMap.png', N'/productMaterialDefaults/93da7ef6-9c75-4be0-b9bc-f5255d837ad5/roughnessMap.png', N'/productMaterialDefaults/93da7ef6-9c75-4be0-b9bc-f5255d837ad5/metalnessMap.png', 7); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (18, N'Corset_Mat1', N'Đai bụng', '0', N'Cao su', N'/productMaterialDefaults/e23ea523-7058-4300-a775-a9c8eda2a692/aoMap.png', N'/productMaterialDefaults/e23ea523-7058-4300-a775-a9c8eda2a692/normalMap.png', N'/productMaterialDefaults/e23ea523-7058-4300-a775-a9c8eda2a692/roughnessMap.png', N'/productMaterialDefaults/e23ea523-7058-4300-a775-a9c8eda2a692/metalnessMap.png', 7); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (19, N'M_CrossDress', N'Toàn bộ', '0', N'Cotton', N'/productMaterialDefaults/b7f5b7ad-96bd-440a-af5f-307f2853fdac/aoMap.png', N'/productMaterialDefaults/b7f5b7ad-96bd-440a-af5f-307f2853fdac/normalMap.png', N'/productMaterialDefaults/b7f5b7ad-96bd-440a-af5f-307f2853fdac/roughnessMap.png', N'/productMaterialDefaults/b7f5b7ad-96bd-440a-af5f-307f2853fdac/metalnessMap.png', 8); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (24, N'Material1199', N'Lớp váy dưới trong', '0', N'Cotton', '', '', '', '', 10); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (25, N'Material1208', N'Lớp váy trên trong', '0', N'Cotton', '', '', '', '', 10); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (26, N'PT_FABRIC_FRONT', N'Váy lớp ngoài', '0', N'Vải lụa', '', '', '', '', 10); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (27, N'FABRIC_1_FRONT_2767', N'Toàn váy', '0', N'Vải lụa', '', '', '', '', 11); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (28, N'Dress', N'Váy', '0', N'Cotton', '', '', '', '', 12); GO
INSERT INTO [ProductSetting] ([ProductSettingID], [ProductPartNameDefault], [ProductPartNameCustom], [IsDefault], [NameMaterialDefault], [AoMap], [NormalMap], [RoughnessMap], [MetalnessMap], [ProductID]) VALUES (29, N'Material.002', N'Đai bụng', '0', N'Nhựa', '', '', '', '', 12); GO
