INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (2, 1, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (3, 1, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (4, 1, 4); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (13, 10, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (14, 10, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (15, 11, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (16, 12, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (17, 2, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (18, 5, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (20, 7, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (21, 13, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (22, 13, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (23, 15, 4); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (24, 15, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (25, 15, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (26, 16, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (27, 16, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (28, 18, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (29, 18, 4); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (30, 17, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (31, 17, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (32, 19, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (33, 19, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (34, 19, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (35, 26, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (36, 26, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (37, 26, 4); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (38, 24, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (39, 24, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (40, 24, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (41, 25, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (42, 25, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (43, 25, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (44, 27, 4); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (45, 27, 1); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (46, 27, 2); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (47, 27, 3); GO
INSERT INTO [ProductSettingMaterial] ([ProductSettingMaterialID], [ProductSettingID], [MaterialID]) VALUES (48, 6, 2); GO
